.SH "DG/UX 5.4 DIFFERENCES"
The WCPU and SIZE columns are not shown, nor is the "last pid" display, as
this information is not available from the kernel.
A "processor utilization" column is added, with the heading C.  This number
reflects a process' relative interactivity, represented by an integer from
0 to 7.  A process with 7 is highly interactive.  A process with 0 is not
considered interactive, but uses mostly CPU resources.
The "nice" processor time is not shown, but a "io_wait" processor state is
added, represented the time spent waiting on I/O operations.  This is
currently always set to zero.

Process are considered "idle" unless they are in "run" or "wait" state.
Process are considered to be "system" processes if they have uid=0 and
ppid=1.
Percent CPU is not maintained by the kernel, and has to be calculated by
top, by dividing the difference in system+user time by the delay period.

The DG/UX 5.4 port was written by Mike Williams <mike@inform.co.nz>.
