#!/bin/sh

if ! which podman > /dev/null 2>&1; then
	echo "podman is not in your path"
	exit 1
fi

CONTAINER_DIR=$(realpath "$(dirname "$0")")
CONTAINER_TAG="pg_top-appimage"

# Use the return code from `podman inspect` to determine if the container image
# needs to be created.
if ! podman inspect $CONTAINER_TAG > /dev/null 2>&1; then
	"${CONTAINER_DIR}/build-appimage-container" || exit 1
fi

podman run \
		--rm \
		-v "${CONTAINER_DIR}/..:/usr/local/src/pg_top:rw,Z" \
		-w /usr/local/src/pg_top \
		$CONTAINER_TAG \
		make -f Makefile.cmake appimage

podman run \
        --rm \
        -v "${CONTAINER_DIR}/..:/usr/local/src/pg_top:rw,Z" \
        -w /usr/local/src/pg_top \
        -u root \
        $CONTAINER_TAG \
        chown -R root:root builds/appimage/
