#!/bin/sh

if ! which podman > /dev/null 2>&1; then
	echo "podman is not in your path"
	exit 1
fi

CONTAINER_DIR=$(realpath "$(dirname "$0")")
CONTAINER_TAG="pg_top-appimage"

ARCH="$(uname -m)"

if [ "${ARCH}" = "arm64" ]; then
	ARCH="aarch64"
fi

cd "$CONTAINER_DIR/.." && \
		podman build \
				--isolation=chroot \
				--build-arg ARCH="${ARCH}" \
				-t "${CONTAINER_TAG}" \
				-f Containerfile.appimage \
				.
